### ISSUE TITLE
Modem Crashes after connecting

### ISSUE THREAD

**Issue by pauldevine** [ssshake/esp8266_modem#14]
Hi there,
Thanks so much for creating such a handy little device. I was using it successfully for a few days, but now after I connect the modem seems to crash and I get what looks like a stack trace or some other debugging message in the console. Example below:

Build Info:
TheOldNet.com
SERIAL WIFI MODEM EMULATOR
BUILD 01152021
GPL3 GITHUB.COM/SSSHAKE/vintage-computer-wifi-modem

My settings are:
AT&V
ACTIVE PROFILE:
BAUD: 38400
SSID: buster
PASS: ******
BUSY MSG: SORRY, SYSTEM IS CURRENTLY BUSY. PLEASE TRY AGAIN LATER.
E1 Q0 V1 &K1 &P1 NET0 PET0 S0:1
SPEED DIAL:
0: theoldnet.com:23
1: bbs.retrocampus.com:23
2: bbs.fozztexx.com:23
3: bbs.eotd.com:23
4: blackflag.acid.org:31337
5: bbs.starbase21.net:23
6: reflections.servebbs.com:23
7: heatwavebbs.com:9640
8: aardmud.org:23
9: dw.kicks-ass.org:1111

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Exception (29):
epc1=0x4000df64 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

>>>stack>>>

ctx: sys
sp: 3fffec10 end: 3fffffb0 offset: 0190
3fffeda0:  40233996 3ffedfc8 00000002 4010057c
3fffedb0:  4022c553 40104a07 3ffecde0 4022c4e8
3fffedc0:  00000002 4022c48f 00000002 4022b5e8
3fffedd0:  4022b611 3fffee80 3ffedfc8 0000001a
3fffede0:  40229084 3fffee80 3ffede74 3ffed800
3fffedf0:  3ffea2c0 3fffee80 3fffee80 00000100
3fffee00:  74737562 7f007265 00000000 00000001
3fffee10:  00000001 00000080 00000003 4022bff7
3fffee20:  402253e5 3ffef8fc 3ffeb58c 03a52943
3fffee30:  ffffffc0 3ffed988 3ffea2d0 3ffedfc8
3fffee40:  3ffecde0 00000020 00000000 40229d7b
3fffee50:  00000000 3ffef8fc ffffffc0 00000000
3fffee60:  00000000 3ffedfc8 00000001 0000000f
3fffee70:  feefeffe 00000000 b99308e7 3ffef210
3fffee80:  00000000 10110101 00640104 0000005b
3fffee90:  3ffea2e4 000000d6 3ffea30f 3ffea2d8
3fffeea0:  00000000 3ffea2e4 3ffea2ec 3ffea2f9
3fffeeb0:  00000000 00000000 3ffea315 3ffea370
3fffeec0:  3ffea332 3ffea34e 00000000 00000000
3fffeed0:  00000000 00000000 00000020 00000000
3fffeee0:  3ffefcc4 402297ee 3ffecde0 3ffef8fc
3fffeef0:  00000000 3ffedfc8 3ffecde0 3ffea2c0
3fffef00:  3ffea2c0 000000fe 00000000 00000020
3fffef10:  00000000 3ffea2ca 40232f2b 3ffecde0
3fffef20:  3ffea2b4 3fffdcc0 3ffe93e8 3ffe93e8
3fffef30:  00000080 3ffecde0 00000000 3ffe84ec
3fffef40:  402327eb 3fffdab0 00000000 4020ea78
3fffef50:  3ffe93e8 40000f49 3fffdab0 40000f49
3fffef60:  40000e19 00000005 00050b7c 00000000
3fffef70:  3fffefc0 aa55aa55 0000008b 40104b0d
3fffef80:  40104b13 00050b7c 00000000 5b2c667f
3fffef90:  4010000d ac792dc7 f19a7df1 1881c815
3fffefa0:  00000000 3fffef3c 00000000 3fffff28
3fffefb0:  3fffffc0 00000000 00000000 feefeffe
3fffefc0:  feefeffe feefeffe feefeffe feefeffe
3fffefd0:  feefeffe feefeffe feefeffe feefeffe
3fffefe0:  feefeffe feefeffe feefeffe feefeffe
3fffeff0:  feefeffe feefeffe feefeffe feefeffe
3ffff000:  feefeffe feefeffe feefeffe feefeffe
3ffff010:  feefeffe feefeffe feefeffe feefeffe
3ffff020:  feefeffe feefeffe feefeffe feefeffe
3ffff030:  feefeffe feefeffe feefeffe feefeffe
3ffff040:  feefeffe feefeffe feefeffe feefeffe
3ffff050:  feefeffe feefeffe feefeffe feefeffe
3ffff060:  feefeffe feefeffe feefeffe feefeffe
3ffff070:  feefeffe feefeffe feefeffe feefeffe
3ffff080:  feefeffe feefeffe feefeffe feefeffe
3ffff090:  feefeffe feefeffe feefeffe feefeffe
3ffff0a0:  feefeffe feefeffe feefeffe feefeffe
3ffff0b0:  feefeffe feefeffe feefeffe feefeffe
3ffff0c0:  feefeffe feefeffe feefeffe feefeffe
3ffff0d0:  feefeffe feefeffe feefeffe feefeffe
3ffff0e0:  feefeffe feefeffe feefeffe feefeffe
3ffff0f0:  feefeffe feefeffe feefeffe feefeffe
3ffff100:  feefeffe feefeffe feefeffe feefeffe
3ffff110:  feefeffe feefeffe feefeffe feefeffe
3ffff120:  feefeffe feefeffe feefeffe feefeffe
3ffff130:  feefeffe feefeffe feefeffe feefeffe
3ffff140:  feefeffe feefeffe feefeffe feefeffe
3ffff150:  feefeffe feefeffe feefeffe feefeffe
3ffff160:  feefeffe feefeffe feefeffe feefeffe
3ffff170:  feefeffe feefeffe feefeffe feefeffe
3ffff180:  feefeffe feefeffe feefeffe feefeffe
3ffff190:  feefeffe feefeffe feefeffe feefeffe
3ffff1a0:  feefeffe feefeffe feefeffe feefeffe
3ffff1b0:  feefeffe feefeffe feefeffe feefeffe
3ffff1c0:  feefeffe feefeffe feefeffe feefeffe
3ffff1d0:  feefeffe feefeffe feefeffe feefeffe
3ffff1e0:  feefeffe feefeffe feefeffe feefeffe
3ffff1f0:  feefeffe feefeffe feefeffe feefeffe
3ffff200:  feefeffe feefeffe feefeffe feefeffe
3ffff210:  feefeffe feefeffe feefeffe feefeffe
3ffff220:  feefeffe feefeffe feefeffe feefeffe
3ffff230:  feefeffe feefeffe feefeffe feefeffe
3ffff240:  feefeffe feefeffe feefeffe feefeffe
3ffff250:  feefeffe feefeffe feefeffe feefeffe
3ffff260:  feefeffe feefeffe feefeffe feefeffe
3ffff270:  feefeffe feefeffe feefeffe feefeffe
3ffff280:  feefeffe feefeffe feefeffe feefeffe
3ffff290:  feefeffe feefeffe feefeffe feefeffe
3ffff2a0:  feefeffe feefeffe feefeffe feefeffe
3ffff2b0:  feefeffe feefeffe feefeffe feefeffe
3ffff2c0:  feefeffe feefeffe feefeffe feefeffe
3ffff2d0:  feefeffe feefeffe feefeffe feefeffe
3ffff2e0:  feefeffe feefeffe feefeffe feefeffe
3ffff2f0:  feefeffe feefeffe feefeffe feefeffe
3ffff300:  feefeffe feefeffe feefeffe feefeffe
3ffff310:  feefeffe feefeffe feefeffe feefeffe
3ffff320:  feefeffe feefeffe feefeffe feefeffe
3ffff330:  feefeffe feefeffe feefeffe feefeffe
3ffff340:  feefeffe feefeffe feefeffe feefeffe
3ffff350:  feefeffe feefeffe feefeffe feefeffe
3ffff360:  feefeffe feefeffe feefeffe feefeffe
3ffff370:  feefeffe feefeffe feefeffe feefeffe
3ffff380:  feefeffe feefeffe feefeffe feefeffe
3ffff390:  feefeffe feefeffe feefeffe feefeffe
3ffff3a0:  feefeffe feefeffe feefeffe feefeffe
3ffff3b0:  feefeffe feefeffe feefeffe feefeffe
3ffff3c0:  feefeffe feefeffe feefeffe feefeffe
3ffff3d0:  feefeffe feefeffe feefeffe feefeffe
3ffff3e0:  feefeffe feefeffe feefeffe feefeffe
3ffff3f0:  feefeffe feefeffe feefeffe feefeffe
3ffff400:  feefeffe feefeffe feefeffe feefeffe
3ffff410:  feefeffe feefeffe feefeffe feefeffe
3ffff420:  feefeffe feefeffe feefeffe feefeffe
3ffff430:  feefeffe feefeffe feefeffe feefeffe
3ffff440:  feefeffe feefeffe feefeffe feefeffe
3ffff450:  feefeffe feefeffe feefeffe feefeffe
3ffff460:  feefeffe feefeffe feefeffe feefeffe
3ffff470:  feefeffe feefeffe feefeffe feefeffe
3ffff480:  feefeffe feefeffe feefeffe feefeffe
3ffff490:  feefeffe feefeffe feefeffe feefeffe
3ffff4a0:  feefeffe feefeffe feefeffe feefeffe
3ffff4b0:  feefeffe feefeffe feefeffe feefeffe
3ffff4c0:  feefeffe feefeffe feefeffe feefeffe
3ffff4d0:  feefeffe feefeffe feefeffe feefeffe
3ffff4e0:  feefeffe feefeffe feefeffe feefeffe
3ffff4f0:  feefeffe feefeffe feefeffe feefeffe
3ffff500:  feefeffe feefeffe feefeffe feefeffe
3ffff510:  feefeffe feefeffe feefeffe feefeffe
3ffff520:  feefeffe feefeffe feefeffe feefeffe
3ffff530:  feefeffe feefeffe feefeffe feefeffe
3ffff540:  feefeffe feefeffe feefeffe feefeffe
3ffff550:  feefeffe feefeffe feefeffe feefeffe
3ffff560:  feefeffe feefeffe feefeffe feefeffe
3ffff570:  feefeffe feefeffe feefeffe feefeffe
3ffff580:  feefeffe feefeffe feefeffe feefeffe
3ffff590:  feefeffe feefeffe feefeffe feefeffe
3ffff5a0:  feefeffe feefeffe feefeffe feefeffe
3ffff5b0:  feefeffe feefeffe feefeffe feefeffe
3ffff5c0:  feefeffe feefeffe feefeffe feefeffe
3ffff5d0:  feefeffe feefeffe feefeffe feefeffe
3ffff5e0:  feefeffe feefeffe feefeffe feefeffe
3ffff5f0:  feefeffe feefeffe feefeffe feefeffe
3ffff600:  feefeffe feefeffe feefeffe feefeffe
3ffff610:  feefeffe feefeffe feefeffe feefeffe
3ffff620:  feefeffe feefeffe feefeffe feefeffe
3ffff630:  feefeffe feefeffe feefeffe feefeffe
3ffff640:  feefeffe feefeffe feefeffe feefeffe
3ffff650:  feefeffe feefeffe feefeffe feefeffe
3ffff660:  feefeffe feefeffe feefeffe feefeffe
3ffff670:  feefeffe feefeffe feefeffe feefeffe
3ffff680:  feefeffe feefeffe feefeffe feefeffe
3ffff690:  feefeffe feefeffe feefeffe feefeffe
3ffff6a0:  feefeffe feefeffe feefeffe feefeffe
3ffff6b0:  feefeffe feefeffe feefeffe feefeffe
3ffff6c0:  feefeffe feefeffe feefeffe feefeffe
3ffff6d0:  feefeffe feefeffe feefeffe feefeffe
3ffff6e0:  feefeffe feefeffe feefeffe feefeffe
3ffff6f0:  feefeffe feefeffe feefeffe feefeffe
3ffff700:  feefeffe feefeffe feefeffe feefeffe
3ffff710:  feefeffe feefeffe feefeffe feefeffe
3ffff720:  feefeffe feefeffe feefeffe feefeffe
3ffff730:  feefeffe feefeffe feefeffe feefeffe
3ffff740:  feefeffe feefeffe feefeffe feefeffe
3ffff750:  feefeffe feefeffe feefeffe feefeffe
3ffff760:  feefeffe feefeffe feefeffe feefeffe
3ffff770:  feefeffe feefeffe feefeffe feefeffe
3ffff780:  feefeffe feefeffe feefeffe feefeffe
3ffff790:  feefeffe feefeffe feefeffe feefeffe
3ffff7a0:  feefeffe feefeffe feefeffe feefeffe
3ffff7b0:  feefeffe feefeffe feefeffe feefeffe
3ffff7c0:  feefeffe feefeffe feefeffe feefeffe
3ffff7d0:  feefeffe feefeffe feefeffe feefeffe
3ffff7e0:  feefeffe feefeffe feefeffe feefeffe
3ffff7f0:  feefeffe feefeffe feefeffe feefeffe
3ffff800:  feefeffe feefeffe feefeffe feefeffe
3ffff810:  feefeffe feefeffe feefeffe feefeffe
3ffff820:  feefeffe feefeffe feefeffe feefeffe
3ffff830:  feefeffe feefeffe feefeffe feefeffe
3ffff840:  feefeffe feefeffe feefeffe feefeffe
3ffff850:  feefeffe feefeffe feefeffe feefeffe
3ffff860:  feefeffe feefeffe feefeffe feefeffe
3ffff870:  feefeffe feefeffe feefeffe feefeffe
3ffff880:  feefeffe feefeffe feefeffe feefeffe
3ffff890:  feefeffe feefeffe feefeffe feefeffe
3ffff8a0:  feefeffe feefeffe feefeffe feefeffe
3ffff8b0:  feefeffe feefeffe feefeffe feefeffe
3ffff8c0:  feefeffe feefeffe feefeffe feefeffe
3ffff8d0:  feefeffe feefeffe feefeffe feefeffe
3ffff8e0:  feefeffe feefeffe feefeffe feefeffe
3ffff8f0:  feefeffe feefeffe feefeffe feefeffe
3ffff900:  feefeffe feefeffe feefeffe feefeffe
3ffff910:  feefeffe feefeffe feefeffe feefeffe
3ffff920:  feefeffe feefeffe feefeffe feefeffe
3ffff930:  feefeffe feefeffe feefeffe feefeffe
3ffff940:  feefeffe feefeffe feefeffe feefeffe
3ffff950:  feefeffe feefeffe feefeffe feefeffe
3ffff960:  feefeffe feefeffe feefeffe feefeffe
3ffff970:  feefeffe feefeffe feefeffe feefeffe
3ffff980:  feefeffe feefeffe feefeffe feefeffe
3ffff990:  feefeffe feefeffe feefeffe feefeffe
3ffff9a0:  feefeffe feefeffe feefeffe feefeffe
3ffff9b0:  feefeffe feefeffe feefeffe feefeffe
3ffff9c0:  feefeffe feefeffe feefeffe feefeffe
3ffff9d0:  feefeffe feefeffe feefeffe feefeffe
3ffff9e0:  feefeffe feefeffe feefeffe feefeffe
3ffff9f0:  feefeffe feefeffe feefeffe feefeffe
3ffffa00:  feefeffe feefeffe feefeffe feefeffe
3ffffa10:  feefeffe feefeffe feefeffe feefeffe
3ffffa20:  feefeffe feefeffe feefeffe feefeffe
3ffffa30:  feefeffe feefeffe feefeffe feefeffe
3ffffa40:  feefeffe feefeffe feefeffe feefeffe
3ffffa50:  feefeffe feefeffe feefeffe feefeffe
3ffffa60:  feefeffe feefeffe feefeffe feefeffe
3ffffa70:  feefeffe feefeffe feefeffe feefeffe
3ffffa80:  feefeffe feefeffe feefeffe feefeffe
3ffffa90:  feefeffe feefeffe feefeffe feefeffe
3ffffaa0:  feefeffe feefeffe feefeffe feefeffe
3ffffab0:  00000002 00000000 00000020 40100364
3ffffac0:  40101b8d feefeffe 00000002 4010175c
3ffffad0:  3ffe93a2 401049ef 3ffecb38 feefeffe
3ffffae0:  00000001 40103bca 3ffed568 feefeffe
3ffffaf0:  4010403b feefeffe feefeffe feefeffe
3ffffb00:  feefeffe feefeffe feefeffe feefeffe
3ffffb10:  40103b03 0000001e 00000002 00040000
3ffffb20:  00002200 feefeffe feefeffe feefeffe
3ffffb30:  401029cc 00080000 40233947 00000001
3ffffb40:  00000001 00000000 00000014 40100364
3ffffb50:  40233996 2c9f0300 4000050c 3fffc278
3ffffb60:  401026b4 3fffc200 00000022 3ffecb38
3ffffb70:  40212bde 00000030 00000004 ffffffff
3ffffb80:  40212bb1 00000000 00000000 000000c0
3ffffb90:  00000012 00000000 00000000 00000003
3ffffba0:  0000000a 40247be0 00000005 3ffffcc0
3ffffbb0:  3ffffcfe 3ffffd60 40216acc 00000030
3ffffbc0:  00000003 00000000 0000000a 00000000
3ffffbd0:  40233996 3ffecb38 3ffef8fc 00000001
3ffffbe0:  00000000 a0000000 00000000 0000001c
3ffffbf0:  00003000 00000005 00003000 00000000
3ffffc00:  3ffffd60 00000000 3ffffd60 40216b96
3ffffc10:  0000a000 3ffffd03 3ffedfc8 3ffef8fc
3ffffc20:  00000000 00000002 40212bb1 00000005
3ffffc30:  3ffffd60 00000005 3ffffd60 40216b96
3ffffc40:  3ffffcc0 3ffffcfe 3ffffc70 00000000
3ffffc50:  3ffffd80 40217209 3fff0938 40216acc
3ffffc60:  3ffffd60 3ffffcfe 3ffffcc0 40212cdc
3ffffc70:  00000005 feefeffe feefeffe 00000000
3ffffc80:  3ffe8304 00000000 0000000a 40247be0
3ffffc90:  3ffffd03 00000003 00000000 402178b4
3ffffca0:  3ffef53c 3ffef308 3ffef6a8 3ffe8c52
3ffffcb0:  00000000 3ffe8c51 3ffffd60 40216fc7
3ffffcc0:  00000000 ffffffff ffffffff 00000000
3ffffcd0:  00000005 00000005 00302064 4010175c
3ffffce0:  3ffed568 40102863 3ffecde0 3fff0ddc
3ffffcf0:  3ffef308 3fff0ddc 3ffef7cc 38330e9c
3ffffd00:  00000000 00000000 0000001f 40100364
3ffffd10:  0000005c 00000000 3fffc228 00000100
3ffffd20:  00000005 00000000 00000020 40100364
3ffffd30:  3ffed4f0 00000000 00000005 4010175c
3ffffd40:  00000005 00000000 00000020 40100364
3ffffd50:  401022f3 3ffecde0 00000005 4010175c
3ffffd60:  3ffe93a5 40104a07 3ffecde0 401024d0
3ffffd70:  401022f3 3ffecde0 00000020 40100364
3ffffd80:  00000037 03a4e382 3ffed800 401024d0
3ffffd90:  3ffe9c20 00000000 00000000 4010175c
3ffffda0:  00000037 03a4e382 40102992 00000100
3ffffdb0:  3ffe9c20 7fffffff 00000000 00000001
3ffffdc0:  00000001 00004208 00000000 4010175c
3ffffdd0:  3ffe9c20 03a4d61f 40102992 03a4e382
3ffffde0:  00000000 00000000 0000001f 40100364
3ffffdf0:  401026b4 3fffc200 3fffc228 401052ad
3ffffe00:  4000050c 00000030 00000010 ffffffff
3ffffe10:  4000dcf0 00000030 00000010 ffffffff
3ffffe20:  4000066d 03a51c2f 4bc6a7f0 4bc6a7f0
3ffffe30:  00000000 ffffffff 00000020 fffffffe
3ffffe40:  00000000 3fffc6fc 00000000 03a51c2f
3ffffe50:  4bc6a7f0 03a51c2f 00000000 00000030
3ffffe60:  4000050c 3fffc6fc 00000000 00000001
3ffffe70:  40206017 00000030 00000010 ffffffff
3ffffe80:  40206017 0000eed8 00418937 00000000
3ffffe90:  00004bc6 00000000 00000020 fffffffe
3ffffea0:  00000000 3fffc6fc 00000000 3ffef04c
3ffffeb0:  3ffeee14 3ffe84d4 3ffef210 00000030
3ffffec0:  00004bc6 00000000 00000020 fffffffe
3ffffed0:  00000000 3fffc6fc 00000000 3ffef1d0
3ffffee0:  00000000 3fffdad0 3ffef210 00000030
3ffffef0:  00000000 4bc6a7f0 d9581062 00000000
3fffff00:  00000000 4bc6a7f0 dbe76c8b 00000000
3fffff10:  00000000 00000000 4bc6a7f0 00000000
3fffff20:  00000000 00000001 4010045c 0000eee5
3fffff30:  00000000 00000000 3ffeed0c 40205c51
3fffff40:  011439c6 00000000 00001388 3ffef210
3fffff50:  00000001 00000001 00000010 401004dd
3fffff60:  007a1200 df094542 3ffef000 4020603c
3fffff70:  00000000 68746100 feefef00 80efeffe
3fffff80:  00000000 00000000 00000001 40100364
3fffff90:  3fffdad0 00000000 3ffef1d0 40100385
3fffffa0:  3fffdad0 00000000 3ffef1d0 4020ec25
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

**Comment by pauldevine** [comment]
I'm realizing the crash only seems to happen with hardware flow-control enabled.

**Comment by ssshake** [comment]
That would make sense and that's a good find. That version of the modem does not support hardware flow. The latest version which frankly is waiting on chips in the mail, that are delayed, is shipping from my store now. 

Sorry for the delay, I had no idea people were making issues on here for me.
