### ISSUE TITLE
Apple IIc Null Modem Cable

### ISSUE THREAD

**Issue by junkjunker** [ssshake/esp8266_modem#24]
Regarding the confusion on vintage-computer-wifi-modem/docs/pin-mapping.md about the Apple IIc cable and whether the pins should cross or be straight through, I can confirm that a cross over cable works on the Apple IIc's Modem Port (labelled "2") with ADTPro.

> Null Modem Cable:
DIN 5 ---> DB9			   
2  (tx) ---> 2  (rx)
3  (gnd) -> 5  (gnd)
4  (rx) ---> 3  (tx)

**Comment by ssshake** [comment]
Thanks updated docs!
