### ISSUE TITLE
Missing commands mean you can't use classic mac OpenTransport PPP

### ISSUE THREAD

**Issue by jonthysell** [ssshake/esp8266_modem#7]
I was trying to use the modem with Apple's OpenTransport PPP for MacOS 7.5.5 but it kept failing because certain commands aren't implemented.

Looking at the debug logs, it looks like it always tries the command `ATX1`, which makes sure that the `CONNECT` string contains the baud rate, i.e. `CONNECT 115200`. Since you already return the baud rate, I think this could be as easy as just returning OK for the command. (To be more accurate you'd want to stop returning the baud rate by default and add another setting so you can use `ATX1` to turn it on and `ATX0` to turn it off.

The other command it tries, if you disable the modem sound, is to call `ATM0` to disable the modem speaker. Since obviously there is no speaker on the device, I see no reason why you couldn't just accept `ATM0`, `ATM1`, `ATM2`, `ATM3`, do nothing, and always return an OK result.

https://en.wikipedia.org/wiki/Hayes_command_set#The_basic_Hayes_command_set

**Comment by ssshake** [comment]
(copy paste from other issue) Great thanks for the submission. I'll do it when I get time or if you know how to change it yourself please do so and submit a PR!

I do have a Mac SE 30 and I plan to test with this device but I haven't gotten around to it yet. I need to make a compatible cable as well.

**Comment by jonthysell** [comment]
> (copy paste from other issue) Great thanks for the submission. I'll do it when I get time or if you know how to change it yourself please do so and submit a PR!
> 
> I do have a Mac SE 30 and I plan to test with this device but I haven't gotten around to it yet. I need to make a compatible cable as well.

Here's what I use, if you're not in the mood to make a cable:

- PCCables.com 6ft DB9 Female to Mini Din 8-pin Male: https://www.amazon.com/gp/product/B00ALULFX0/
- DB9 Null Modem Adapter Male to Male: https://www.amazon.com/dp/B07GV5PGJ5

**Comment by ssshake** [comment]
Thanks! I recently received a 10 pack of null modem adapters. I have a db25 to din 8 cable from a US robotics 28.8 modem that came with my Mac LC575. I will convert that to DB9 and run a test. 

Can you help me understand why I need a null modem adapter for this?

**Comment by jonthysell** [comment]
> Can you help me understand why I need a null modem adapter for this?

While not labeled as such, that particular cable I linked is already wired as a null modem cable. So I add a null modem adapter to change it back so it works with your modem.

**Comment by ssshake** [comment]
Thanks for your help on this. I completely forgot about this conversation but it's probably got a lot to do with me stocking mac cables now on my store. I had to get them custom made from a factory.

Also since a community member has added PPP support to the firmware. You should have no problem doing what you were originally trying to do!
