### ISSUE TITLE
Add a "passthrough" mode for unimplemented AT commands

### ISSUE THREAD

**Issue by jonthysell** [ssshake/esp8266_modem#8]
Some software tries to call Hayes commands that aren't implemented, but really don't apply to the device anyway. See issue #7.

Rather than having to implement every (potentially no-op) command, what if there was a mode that, when enabled, just checked if the command starts with `AT` just always returned OK. You could add it as a final else-if statement when you're checking the command string.

It might mean that the software sending the commands is expecting some different behavior, but for no-op things (like changing the "speaker volume") it might broaden the compatibility.

**Comment by ssshake** [comment]
Great thanks for the submission. I'll do it when I get time or if you know how to change it yourself please do so and submit a PR!

**Comment by ssshake** [comment]
This is fixed now and please look at the new main repo for this project under The Old Net org: https://github.com/TheOldNet/vintage-computer-wifi-modem
