### ISSUE TITLE
Add development environment setup steps

### ISSUE THREAD

**Issue by jonthysell** [ssshake/esp8266_modem#9]
I have opened a couple bugs (#7, #8) both of which I could fix myself. I've looked through the code, and I've done Arduino dev before. But I'm not sure what the setup is for this device, and I don't want to brick the one I physically have.

Can you add dev setup docs, like Arduino IDE settings, libraries you need, etc.?

I'd gladly contribute a PR or two to improve the code.

**Comment by ssshake** [comment]
I'm sorry that I never responded to this. This is my first time reading it and I'll pay attention to this issue tracker regularly now. 

The set up instructions are like this. https://randomnerdtutorials.com/how-to-install-esp8266-board-arduino-ide/
